---
- name: Install the required packages
  apt:
    pkg: "{{ glusterfs_dev_requirements }}"
    state: latest

- name: Ensure directory for source exists
  file:
    path: "{{ glusterfs_dev_dir }}"
    state: directory

# If there are local changes, git checkout etc doesn't work.
# The directory may not exist in first run, which is not an error
- name: Clean glusterfs source directory
  shell: |
      git clean -f
      git stash
  ignore_errors: true
  args:
    chdir: "{{ glusterfs_dev_dir }}"

- name: Git checkout glusterfs
  git:
    depth: 1
    clone: yes
    update: yes
    repo: "{{ glusterfs_git_repo }}"
    dest: "{{ glusterfs_dev_dir }}"
    version: "v{{ glusterfs_git_version }}"

- name: Retrieve the installed GlusterFS version
  command: gluster --version | head -1 | grep -oP "[0-9].[0-9]"
  register: glusterfs_version_check
  changed_when: glusterfs_version_check.stdout.find(glusterfs_git_version) == -1
  ignore_errors: true

- name: Build from source
  when: glusterfs_version_check.changed or glusterfs_version_check.failed
  block:
  # Run autogen and configure to generate makefile
  - name: Generate configure file
    command: ./autogen.sh
    args:
      chdir: "{{ glusterfs_dev_dir }}"

  - name: Run configure to generate Makefile for building GlusterFS
    command: ./configure "{{ wolibtirpc | default('') }}"
    args:
      chdir: "{{ glusterfs_dev_dir }}"

  # There can be some generated .c files, which gives an warning of 'overwriting'
  # if make clean is not done before
  - name: Clean glusterfs source directory
    make:
      chdir: "{{ glusterfs_dev_dir }}"
      target: clean

  # Can't do make install in a single command with this module
  - name: Build and install GlusterFS
    make:
      chdir: "{{ glusterfs_dev_dir }}"
      target: install

  # Can't do make install in a single command with this module
  - name: Clean build directory
    make:
      chdir: "{{ glusterfs_dev_dir }}"
      target: distclean

  - name: Reload shared libraries upon successful build
    command: /sbin/ldconfig -v
    args:
      chdir: "{{ glusterfs_dev_dir }}"
